### ISSUE TITLE
Node Expand not working

### ISSUE THREAD

**Issue by savanthvinay** [sebbert/rete-reorder-nodes-plugin#12]
Hi @sebbert 
I have used this plugin ,After using my node has accordion on click of node its reordering but accordion is not working/Expanding. Can u please help me out with this problem.

**Comment by sebbert** [comment]
Hi, this repository has not been maintained for several years. I don't use rete anymore, so I unfortunately cannot help you. But the code is very simple, I'm sure you can figure it out: https://github.com/sebbert/rete-reorder-nodes-plugin/blob/master/src/index.ts
